services:
  mercure:
    container_name: mercure
    image: dunglas/mercure:latest
    restart: always
    environment:
      SERVER_NAME: :80
      MERCURE_PUBLISHER_JWT_KEY: dev
      MERCURE_SUBSCRIBER_JWT_KEY: dev
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/data
      - config:/config

volumes:
  data:
  config:
