services:
  pocketbase:
    container_name: pocketbase
    image: ghcr.io/muchobien/pocketbase:latest
    restart: always
    environment:
      PB_HOST: 0.0.0.0
      PB_PORT: 8090
      PB_ADMIN_EMAIL: dev@gmail.com
      PB_ADMIN_PASSWORD: dev@gmail.com
    ports:
      - "8090:8090"
    volumes:
      - data:/pb_data
      - public:/pb_public #optional
      - hooks:/pb_hooks

volumes:
  data:
  public:
  hooks:
