services:
  valkey:
    container_name: valkey
    image: valkey/valkey:latest
    restart: always
    command: valkey-server --requirepass dev --save 60 1 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - data:/data

volumes:
  data:
